import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { rimeConfig } from '../server/config.js';
import { forTheEar } from '../server/ear.js';

/**
 * Before/after delivery evidence.
 *
 * The rules for a prompting or delivery claim are explicit: hold the model and
 * voice constant, render at least two text variants, save the clips, and say
 * which wording changed the result. That is exactly what this does.
 *
 * For each fixture it renders TWO wav files through the same Rime model,
 * speaker, language and sampling rate:
 *
 *   evidence/clips/<id>.raw.wav   - the catalog string as written
 *   evidence/clips/<id>.ear.wav   - the same string through server/ear.ts
 *
 * and writes evidence/pronunciation.md listing both texts, the rules that
 * fired, and what to listen for. Nothing here is scored automatically: the
 * claim is about intelligibility, and the only honest instrument for that is a
 * pair of clips and a human ear.
 *
 *   npm run pronounce
 */

loadEnv();

async function main() {
  const cfg = rimeConfig();
  if (!cfg.apiKey) {
    console.error('\n  RIME_API_KEY is not set. Cannot render clips.\n');
    process.exit(2);
  }

  const cases: { id: string; text: string; listenFor: string }[] = JSON.parse(
    readFileSync(join(process.cwd(), 'fixtures/pronunciation.json'), 'utf8'),
  ).cases;

  const outDir = join(process.cwd(), 'evidence/clips');
  mkdirSync(outDir, { recursive: true });

  const rows: string[] = [];
  console.log(`\n  Rendering ${cases.length} fixtures x 2 variants`);
  console.log(`  held constant: modelId=${cfg.modelId} speaker=${cfg.speaker} lang=${cfg.lang} samplingRate=${cfg.samplingRate}\n`);

  for (const c of cases) {
    const { text: after, rulesFired } = forTheEar(c.text);
    const rawMs = await render(cfg, c.text, join(outDir, `${c.id}.raw.wav`));
    const earMs = await render(cfg, after, join(outDir, `${c.id}.ear.wav`));

    console.log(`  ${c.id.padEnd(16)} raw ${String(rawMs).padStart(5)}ms   ear ${String(earMs).padStart(5)}ms   rules: ${rulesFired.join(', ') || '-'}`);

    rows.push(
      [
        `### ${c.id}`,
        '',
        `**Written (raw):** \`${c.text}\``,
        '',
        `**Spoken (after \`server/ear.ts\`):** \`${after}\``,
        '',
        `**Rules fired:** ${rulesFired.length ? rulesFired.map((r) => `\`${r}\``).join(', ') : '_none_'}`,
        '',
        `**Listen for:** ${c.listenFor}`,
        '',
        `**Clips:** [\`${c.id}.raw.wav\`](clips/${c.id}.raw.wav) vs [\`${c.id}.ear.wav\`](clips/${c.id}.ear.wav)`,
        '',
      ].join('\n'),
    );
  }

  const md = [
    '# Pronunciation and controlled delivery: before / after',
    '',
    '_Generated by `npm run pronounce`. Do not hand-edit._',
    '',
    'Model, speaker, language and sampling rate are held constant across every pair;',
    'the **only** variable is the text. Each pair answers one question: does the',
    'technician get the part number right the first time, without asking again?',
    '',
    '| field | value |',
    '| --- | --- |',
    `| modelId | \`${cfg.modelId}\` |`,
    `| speaker | \`${cfg.speaker}\` |`,
    `| lang | \`${cfg.lang}\` |`,
    `| samplingRate | \`${cfg.samplingRate}\` |`,
    `| endpoint | \`${cfg.httpUrl}\` |`,
    `| rendered at | ${new Date().toISOString()} |`,
    '',
    '> These are **uncached** renders: each request is a fresh POST. Timings in the',
    '> console output include TLS setup and are not comparable to the warm ws3',
    '> figures in `RIME_EVIDENCE.md`.',
    '',
    ...rows,
  ].join('\n');

  writeFileSync(join(process.cwd(), 'evidence/pronunciation.md'), md);
  console.log(`\n  wrote evidence/pronunciation.md and ${cases.length * 2} clips\n`);
}

async function render(cfg: ReturnType<typeof rimeConfig>, text: string, path: string): Promise<number> {
  const t0 = Date.now();
  const res = await fetch(cfg.httpUrl, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${cfg.apiKey}`,
      'Content-Type': 'application/json',
      Accept: 'audio/wav',
    },
    body: JSON.stringify({
      speaker: cfg.speaker,
      text,
      modelId: cfg.modelId,
      lang: cfg.lang,
      samplingRate: cfg.samplingRate,
    }),
  });
  if (!res.ok) throw new Error(`rime ${res.status}: ${await res.text()}`);
  writeFileSync(path, Buffer.from(await res.arrayBuffer()));
  return Date.now() - t0;
}

function loadEnv() {
  for (const f of ['.env.local', '.env']) {
    if (!existsSync(f)) continue;
    for (const line of readFileSync(f, 'utf8').split('\n')) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (!m) continue;
      if (process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '');
    }
  }
}

void main();
